{{- if .Values.service -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.name }}
spec:
  provider: vault
  secretObjects:
  - data:
    - key: password
      objectName: db-password
    secretName: dbpass
    type: Opaque
  parameters:
    vaultAddress: "http://vault.vault:8200"
    roleName: {{ .Values.namespace }}-role
    objects: |
      - objectName: "db-password"
        secretPath: "yesodot/"{{ .Values.namespace }}"/"{{ .Values.secret.name }}
        secretKey: "password"
