kind: Pod
apiVersion: v1
metadata:
  name: {{ .Values.name }}
spec:
  serviceAccountName: {{ .Values.namespace }}-sa
  containers:
  - image: {{ .Values.image.name }}
    name: {{ .Values.name }}
    env:
    {{- range .Values.config.env }}
    - name: {{ .name }}
      valueFrom:
        secretKeyRef:
          name: dbpass
          key: password
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: {{ .Values.secret.name }}
